<?php
// auto-generated by sfRoutingConfigHandler
// date: 2015/09/01 13:56:08
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'website',
      'action' => 'display',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'url_rewrite' => 
  array (
    0 => '/:rewriteUrl',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'rewriteUrl',
    ),
    3 => 
    array (
      'rewriteUrl' => 1,
    ),
    4 => 
    array (
      'module' => 'website',
      'action' => 'display',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_index' => 
  array (
    0 => '/:module',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'module',
    ),
    3 => 
    array (
      'module' => 1,
    ),
    4 => 
    array (
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
