<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/09/01 17:36:51
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
