default:
  http_metas:
    content-type: text/html

  metas:
    title:        
    robots:       index, follow
    description:  
    keywords:     
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
